import test from'node:test';import assert from'node:assert/strict';import fs from'node:fs';import path from'node:path';import{spawn}from'node:child_process';import{ROOT,empty}from'../server/store.mjs';
test('本地 API 编辑、来源标注、复习、快照恢复与权限边界',async()=>{
 const data=path.join(ROOT,'tmp','api-test-'+Date.now());fs.mkdirSync(data,{recursive:true});const db=empty();db.sources=[{id:'s1',kind:'pdf',pageCount:4,title:'测试讲义'}];fs.writeFileSync(path.join(data,'platform.json'),JSON.stringify(db),'utf8');const port=14186;const p=spawn(process.execPath,['server/index.mjs'],{cwd:ROOT,env:{...process.env,GROWTH_DATA_DIR:data,PORT:String(port)},windowsHide:true,stdio:'pipe'});let started=false;p.stdout.on('data',()=>{started=true;});try{for(let i=0;i<50&&!started;i++)await new Promise(r=>setTimeout(r,100));const base=`http://127.0.0.1:${port}`;const b=await(await fetch(base+'/api/bootstrap')).json();assert.equal(b.mode,'local');const post=async(endpoint,payload={},origin)=>{const r=await fetch(base+'/api/'+endpoint,{method:'POST',headers:{'Content-Type':'application/json','X-Growth-Token':b.token,...origin?{Origin:origin}:{}},body:JSON.stringify(payload)});return {status:r.status,data:await r.json()};};
 assert.equal((await post('records',{},'https://untrusted.example')).status,403);assert.equal((await fetch(base+'/api/records',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'})).status,403);
 const created=await post('records',{record:{kind:'knowledge',title:'中文知识卡',body:'原文与分析分开',subject:'xingce',tags:[],links:[],sourceRefs:[{sourceId:'s1',page:2,regions:[{x:.1,y:.1,w:.4,h:.2}]}]}});assert.equal(created.status,200);const card=created.data;assert.equal((await(await fetch(base+'/api/records/'+card.id)).json()).title,'中文知识卡');
 const review=await post('review',{id:card.id,revision:card.revision,rating:'掌握'});assert.equal(review.status,200);assert.ok(review.data.nextReview);assert.equal((await post('records',{record:{...card,body:'过时覆盖'},revision:card.revision})).status,409);
 const snap=await post('backup');await post('records',{record:{...review.data,title:'后来修改'},revision:review.data.revision});assert.equal((await post('restore',{name:snap.data.name})).status,200);assert.equal((await(await fetch(base+'/api/records/'+card.id)).json()).title,'中文知识卡');assert.equal((await post('restore',{name:'../../platform.json'})).status,400);
 assert.equal((await post('upload',{filename:'bad.pdf',base64:Buffer.from('not a pdf').toString('base64')})).status,400);
 }finally{p.kill();}
});
