import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {fileURLToPath} from 'node:url';
export const ROOT=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
export const DATA=process.env.GROWTH_DATA_DIR||path.join(ROOT,'data');
export const STORE=path.join(DATA,'platform.json');
export const now=()=>new Date().toISOString();
export const hash=v=>crypto.createHash('sha256').update(typeof v==='string'||Buffer.isBuffer(v)?v:JSON.stringify(v)).digest('hex');
export const uid=(prefix='record')=>`${prefix}-${crypto.randomUUID()}`;
export const idFor=(prefix,id)=>`${prefix}-${hash(String(id)).slice(0,24)}`;
export function atomic(file,value){fs.mkdirSync(path.dirname(file),{recursive:true});const tmp=file+'.'+crypto.randomUUID()+'.tmp';fs.writeFileSync(tmp,typeof value==='string'||Buffer.isBuffer(value)?value:JSON.stringify(value,null,2),'utf8');fs.renameSync(tmp,file);}
export function empty(){return {schemaVersion:1,version:0,updatedAt:now(),records:[],sources:[],conflicts:[],archives:[],imports:[],growth:{},reviewSettings:{dailyCapacity:12},publication:{state:'尚未发布'}};}
export function read(){return fs.existsSync(STORE)?JSON.parse(fs.readFileSync(STORE,'utf8')):empty();}
export function write(db){db.version++;db.updatedAt=now();atomic(STORE,db);return db;}
export function backup(db=read()){const name=`snapshot-${now().replace(/[:.]/g,'-')}-${db.version}.json`;atomic(path.join(DATA,'backups',name),db);return name;}
export function dateCN(value=new Date()){return new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Shanghai'}).format(value);}
export function reviewDate(rating,stage=0,base=new Date()){const nextStage=rating==='忘记'?0:rating==='模糊'?Math.max(0,stage):Math.min(stage+1,4);const days=rating==='忘记'?1:rating==='模糊'?3:[1,3,7,14,30][Math.min(stage,4)];const date=new Date(`${dateCN(base)}T12:00:00+08:00`);date.setUTCDate(date.getUTCDate()+days);return {nextReview:dateCN(date),reviewStage:nextStage};}
const blocked=/^(?:storedPath|sourcePath|originalPath|localPath|token|accessToken|mobileAccessToken|apiKey|secret|password)$/i;
export function publicClean(v){if(Array.isArray(v))return v.map(publicClean);if(v&&typeof v==='object')return Object.fromEntries(Object.entries(v).filter(([k])=>!blocked.test(k)).map(([k,a])=>[k,publicClean(a)]));if(typeof v==='string'){if(/^(?:[A-Za-z]:[\\/]|file:\/\/)/.test(v))return '本机原文件';return v.replace(/[A-Za-z]:\\[^\r\n"<>]+/g,'本机原文件');}return v;}
export function summary(r){return {id:r.id,kind:r.kind,title:r.title,excerpt:(r.body||'').replace(/[#*`]/g,'').slice(0,180),subject:r.subject||'',topic:r.topic||'',date:r.date||'',tags:r.tags||[],sourceRefs:r.sourceRefs||[],links:r.links||[],nextReview:r.nextReview||'',activationStatus:r.activationStatus||'',verificationStatus:r.verificationStatus||'',starred:!!r.starred,revision:r.revision,archived:!!r.archived};}
export function catalog(db){return {schemaVersion:1,version:db.version,updatedAt:db.updatedAt,records:db.records.filter(r=>!r.archived).map(summary),sources:publicClean(db.sources).map(({pages,...s})=>({...s,pageMetadata:!!pages})),counts:{records:db.records.filter(r=>!r.archived).length,sources:db.sources.length,conflicts:db.conflicts.length},reviewSettings:db.reviewSettings};}
export function validateRecord(input,db,existing){if(!input||typeof input!=='object')throw new Error('记录格式无效');if(!String(input.title||'').trim())throw new Error('请填写标题');if(String(input.title).length>240||String(input.body||'').length>500000)throw new Error('内容超出允许长度');if(!['knowledge','review','memory','note','article','quote','growth','practice','error','weekly','letter','common','fortune'].includes(input.kind))throw new Error('记录类型无效');for(const ref of input.sourceRefs||[]){if(ref.sourceId){const s=db.sources.find(s=>s.id===ref.sourceId);if(!s)throw new Error('关联原资料不存在');if(!Number.isInteger(ref.page)||ref.page<1||ref.page>s.pageCount)throw new Error('来源页码超出范围');for(const b of ref.regions||[]){if(!['x','y','w','h'].every(k=>Number.isFinite(b[k]))||b.x<0||b.y<0||b.w<=0||b.h<=0||b.x+b.w>1.00001||b.y+b.h>1.00001)throw new Error('标注区域超出页面');}}if(ref.url&&!/^https?:\/\//i.test(ref.url))throw new Error('来源链接须为 HTTP(S)');}for(const id of input.links||[])if(!db.records.some(r=>r.id===id)&&id!==existing?.id)throw new Error('关联记录不存在');return {...existing,...input,id:existing?.id||uid(),revision:(existing?.revision||0)+1,edited:true,createdAt:existing?.createdAt||now(),updatedAt:now()};}
export function saveRecord(db,input,revision){const old=db.records.find(r=>r.id===input.id);if(input.id&&!old)throw new Error('记录不存在');if(old&&revision!==old.revision){const e=new Error('这条记录已被其他窗口更新，请重新打开后保存。');e.status=409;throw e;}const row=validateRecord(input,db,old);if(old){db.archives.push({recordId:old.id,at:now(),record:old});db.records[db.records.indexOf(old)]=row;}else db.records.push(row);return row;}
export function mergeImported(db,rows,sources=[]){let added=0,updated=0,conflicts=0;for(const incoming of rows){incoming.importHash=hash({...incoming,revision:undefined,importHash:undefined});const existing=db.records.find(r=>r.id===incoming.id);if(!existing){db.records.push({...incoming,revision:1});added++;}else if(existing.importHash!==incoming.importHash){if(existing.edited){if(!db.conflicts.some(c=>c.recordId===incoming.id&&c.incoming.importHash===incoming.importHash)){db.conflicts.push({id:uid('conflict'),recordId:incoming.id,incoming,at:now()});conflicts++;}}else{db.records[db.records.indexOf(existing)]={...incoming,revision:existing.revision+1};updated++;}}}for(const s of sources){const old=db.sources.find(x=>x.id===s.id);if(old)Object.assign(old,s);else db.sources.push(s);}return {added,updated,conflicts,total:db.records.length};}
