import fs from 'node:fs';
import path from 'node:path';
import {spawn} from 'node:child_process';
import {ROOT,DATA,read,backup,atomic,now,hash} from '../server/store.mjs';
import {exportSite} from './export.mjs';
import {verify} from './verify.mjs';
import {syncCode} from './sync-code.mjs';
const repo='PF11223333/growth-study-platform',url='https://pf11223333.github.io/growth-study-platform/';
const statusFile=path.join(DATA,'publish-status.json'),wait=ms=>new Promise(r=>setTimeout(r,ms));
function step(label){console.log(label);atomic(statusFile,{state:'发布中',step:label,updatedAt:now()});}
function run(cmd,args,{input='',quiet=false,timeout=240000}={}){return new Promise((resolve,reject)=>{const p=spawn(cmd,args,{cwd:ROOT,windowsHide:true,stdio:['pipe','pipe','pipe']});let out='',err='';const timer=setTimeout(()=>{p.kill();reject(new Error(cmd+' 网络操作超时'));},timeout);p.stdout.on('data',b=>{out+=b;if(!quiet)process.stdout.write(b);});p.stderr.on('data',b=>{err+=b;if(!quiet)process.stderr.write(b);});p.on('error',e=>{clearTimeout(timer);reject(e);});p.on('close',c=>{clearTimeout(timer);c===0?resolve(out):reject(new Error(`${cmd} 退出 ${c}: ${err.slice(-1200)||out.slice(-1200)}`));});p.stdin.end(input);});}
async function gh(endpoint,method='GET',data){for(let attempt=0;;attempt++){try{const out=await run('gh',['api',endpoint,...method!=='GET'?['--method',method]:[],...data?['--input','-']:[]],{input:data?JSON.stringify(data):'',quiet:true,timeout:45000});return out.trim()?JSON.parse(out):{};}catch(e){if(method!=='GET'||attempt>=3||!/EOF|reset|timeout|超时|TLS|502|503|504|connect/i.test(e.message))throw e;await wait(2000*(attempt+1));}}}
async function release(tag,body){try{return await gh(`repos/${repo}/releases/tags/${tag}`);}catch(e){if(!e.message.includes('404'))throw e;return gh(`repos/${repo}/releases`,'POST',{tag_name:tag,name:tag,body,prerelease:tag!=='materials'});}}
function split(file,namespace='materials'){const filename=path.basename(file),dir=path.join(DATA,'transfer-parts',namespace,filename);fs.mkdirSync(dir,{recursive:true});const fd=fs.openSync(file,'r'),buffer=Buffer.alloc(8*1024*1024),parts=[];let n=0,i=0;try{while((n=fs.readSync(fd,buffer,0,buffer.length,null))>0){const part=path.join(dir,filename+'.part'+String(i++).padStart(4,'0'));if(!fs.existsSync(part)||fs.statSync(part).size!==n)atomic(part,buffer.subarray(0,n));parts.push(part);}}finally{fs.closeSync(fd);}return parts;}
async function transfer(tag,files,label){const remote=await gh(`repos/${repo}/releases/tags/${tag}`),ready=new Map(remote.assets.filter(a=>a.state==='uploaded').map(a=>[a.name,a.size]));const queue=files.filter(f=>ready.get(path.basename(f))!==fs.statSync(f).size),total=queue.length;let completed=0;
 const worker=async()=>{while(queue.length){const file=queue.shift();for(let attempt=0;;attempt++){try{await run('gh',['release','upload',tag,file,'--repo',repo,'--clobber'],{quiet:true});break;}catch(e){const check=await gh(`repos/${repo}/releases/tags/${tag}`);if(check.assets.some(a=>a.name===path.basename(file)&&a.state==='uploaded'&&a.size===fs.statSync(file).size))break;if(attempt>=3)throw e;await wait(2500*(attempt+1));}}completed++;step(`${label}：${completed}/${total} 个分段已传输`);}};
 const outcomes=await Promise.allSettled(Array.from({length:4},worker)),errors=outcomes.filter(r=>r.status==='rejected');if(errors.length)throw new Error('部分分段未上传，重试会继续已完成的进度。'+errors.map(e=>e.reason.message).join('；'));}
async function remoteText(target){return run(process.env.GROWTH_PYTHON||'python',['-I','-c','import urllib.request,sys; sys.stdout.buffer.write(urllib.request.urlopen(urllib.request.Request(sys.argv[1],headers={"User-Agent":"growth-platform-verifier","Cache-Control":"no-cache"}),timeout=30).read())',target],{quiet:true,timeout:40000});}
fs.mkdirSync(DATA,{recursive:true});const lock=path.join(DATA,'publish.lock');let descriptor;try{descriptor=fs.openSync(lock,'wx');}catch{throw new Error('已有发布任务，请等待完成。');}
try{
 step('保存快照并构建');const db=read();backup(db);await run(process.execPath,[path.join(ROOT,'node_modules/typescript/bin/tsc'),'--noEmit']);await run(process.execPath,[path.join(ROOT,'node_modules/vite/bin/vite.js'),'build']);const version=exportSite(db),audit=verify(db);console.log(JSON.stringify(audit));
 step('同步平台源码与部署流程');syncCode();
 const originals=await release('materials','原始学习资料。分段用于可靠传输，完整文件经 SHA-256 核验后合并。');
 const materialParts=[];for(const s of db.sources){if(s.missing||originals.assets.some(a=>a.name===s.filename&&a.size===s.size&&a.state==='uploaded'))continue;materialParts.push(...split(path.join(DATA,'originals',s.filename)));}await transfer('materials',materialParts,'原资料上传');
 step('打包已验证的公开站点');const tag=`site-v${db.version}-${version.appHash.slice(0,12)}`,bundle=path.join(DATA,tag,'site.zip');fs.mkdirSync(path.dirname(bundle),{recursive:true});
 if(!fs.existsSync(bundle))await run(process.env.GROWTH_PYTHON||'python',['-I','-c','import zipfile,pathlib,sys; root=pathlib.Path(sys.argv[1]); z=zipfile.ZipFile(sys.argv[2],"w",zipfile.ZIP_STORED); [z.write(p,p.relative_to(root).as_posix()) for p in sorted(root.rglob("*")) if p.is_file()]; z.close()',path.join(ROOT,'dist'),bundle]);
 await release(tag,'Validated static website bundle.');await transfer(tag,split(bundle,tag),'站点上传');
 step('启动 GitHub Pages 部署与原文件校验');try{const pages=await gh(`repos/${repo}/pages`);if(pages.build_type!=='workflow')await gh(`repos/${repo}/pages`,'PUT',{build_type:'workflow'});}catch(e){if(!e.message.includes('404'))throw e;await gh(`repos/${repo}/pages`,'POST',{build_type:'workflow'});}
 await gh(`repos/${repo}/actions/workflows/pages.yml/dispatches`,'POST',{ref:'main',inputs:{release_tag:tag}});
 let verified=false,lastError='';for(let attempt=0;attempt<48;attempt++){
  try{const remote=JSON.parse(await remoteText(`${url}version.json?v=${Date.now()}`));if(remote.version===version.version&&remote.catalogHash===version.catalogHash&&remote.appHash===version.appHash){const raw=await remoteText(`${url}data/catalog.json?v=${Date.now()}`);if(hash(raw)!==version.catalogHash)throw new Error('公网目录哈希不匹配');const records=db.records.filter(r=>!r.archived);for(const r of[records[0],records[Math.floor(records.length/2)],records.at(-1)]){const got=JSON.parse(await remoteText(`${url}data/records/${r.id}.json?v=${Date.now()}`));if(got.id!==r.id||got.title!==r.title)throw new Error('公网详情内容不匹配');}const materials=await gh(`repos/${repo}/releases/tags/materials`);for(const s of db.sources.filter(s=>!s.missing))if(!materials.assets.some(a=>a.name===s.filename&&a.size===s.size&&a.state==='uploaded'))throw new Error('完整原文件尚未就绪');verified=true;break;}}catch(e){lastError=e.message;}
  if(attempt%6===0)step('等待 Pages 完成，随后核对公网版本、内容和原文件');await wait(10000);
 }
 if(!verified)throw new Error('本地与上传已完成，公网尚未通过回读。'+lastError);const result={state:'公网已更新',url,version:version.version,appHash:version.appHash,catalogHash:version.catalogHash,verifiedAt:now(),audit};atomic(statusFile,result);console.log(JSON.stringify(result));
}catch(e){atomic(statusFile,{state:'发布失败',error:e.message,at:now(),localVersion:read().version});console.error(e);process.exitCode=1;}finally{if(descriptor!==undefined)fs.closeSync(descriptor);if(fs.existsSync(lock))fs.unlinkSync(lock);}
