import fs from'node:fs';import path from'node:path';import{spawn}from'node:child_process';import{ROOT,DATA,read,backup,atomic,now,hash}from'../server/store.mjs';import{exportSite}from'./export.mjs';import{verify}from'./verify.mjs';
import{syncCode}from'./sync-code.mjs';
const repo='PF11223333/growth-study-platform',url='https://pf11223333.github.io/growth-study-platform/',statusFile=path.join(DATA,'publish-status.json');
function run(cmd,args,options={}){return new Promise((resolve,reject)=>{const p=spawn(cmd,args,{cwd:options.cwd||ROOT,windowsHide:true,stdio:['pipe','pipe','pipe']});let stdout='',stderr='';p.stdout.on('data',b=>{stdout+=b;if(!options.quiet)process.stdout.write(b);});p.stderr.on('data',b=>{stderr+=b;process.stderr.write(b);});p.on('error',reject);p.on('close',code=>code===0?resolve(stdout):reject(new Error(`${cmd} 退出 ${code}: ${stderr.slice(-1400)||stdout.slice(-1400)}`)));p.stdin.end(options.input||'');});}
const gh=(endpoint,method='GET',data)=>run('gh',['api',endpoint,...method!=='GET'?['--method',method]:[],...data?['--input','-']:[]],{input:data?JSON.stringify(data):undefined,quiet:true}).then(s=>s.trim()?JSON.parse(s):{});
const step=(label)=>{console.log(label);atomic(statusFile,{state:'发布中',step:label,startedAt:now()});};
const wait=ms=>new Promise(r=>setTimeout(r,ms));
async function remoteText(target){return run(process.env.GROWTH_PYTHON||'python',['-I','-c','import urllib.request,sys; sys.stdout.buffer.write(urllib.request.urlopen(urllib.request.Request(sys.argv[1],headers={"User-Agent":"growth-platform-verifier","Cache-Control":"no-cache"}),timeout=35).read())',target],{quiet:true});}
const lock=path.join(DATA,'publish.lock');fs.mkdirSync(DATA,{recursive:true});let descriptor;try{descriptor=fs.openSync(lock,'wx');}catch{throw new Error('已有发布进程，请等待完成；若上次异常退出，请检查后移除本地 publish.lock。');}
try{
 step('保存发布快照');const db=read();backup(db);const manifestVersion=db.version;
 step('构建统一界面');await run(process.execPath,[path.join(ROOT,'node_modules','typescript','bin','tsc'),'--noEmit']);await run(process.execPath,[path.join(ROOT,'node_modules','vite','bin','vite.js'),'build']);const version=exportSite(db);const audit=verify(db);console.log(JSON.stringify(audit));
 step('检查 GitHub 项目');try{await gh(`repos/${repo}`);}catch(e){if(!e.message.includes('404'))throw e;await run('gh',['repo','create',repo,'--public','--description','向内生长 · 学习资料与复盘平台']);}
 step('同步平台源码与部署流程');syncCode();
 step('上传完整原始资料');let release;try{release=await gh(`repos/${repo}/releases/tags/materials`);}catch(e){if(!e.message.includes('404'))throw e;release=await gh(`repos/${repo}/releases`,'POST',{tag_name:'materials',name:'学习原资料',body:'原文件按内容 SHA-256 命名，与站内逐页预览关联。',draft:false,prerelease:false});}
 for(const source of db.sources){if(source.missing)continue;const match=release.assets?.find(a=>a.name===source.filename);if(match&&match.size===source.size)continue;step(`上传原资料：${source.title}`);await run('gh',['release','upload','materials',path.join(DATA,'originals',source.filename),'--repo',repo,'--clobber']);}
 step('打包已验证的公开站点');const tag='site-v'+manifestVersion+'-'+Date.now();const bundle=path.join(DATA,'site.zip');await run(process.env.GROWTH_PYTHON||'python',['-I','-c','import zipfile,pathlib,sys; root=pathlib.Path(sys.argv[1]); z=zipfile.ZipFile(sys.argv[2],"w",zipfile.ZIP_STORED); [z.write(p,p.relative_to(root).as_posix()) for p in root.rglob("*") if p.is_file()]; z.close()',path.join(ROOT,'dist'),bundle]);
 await gh(`repos/${repo}/releases`,'POST',{tag_name:tag,name:'Reading edition v'+manifestVersion,body:'Validated static website bundle.',prerelease:true});
 step('上传站点并触发 Pages 部署');await run('gh',['release','upload',tag,bundle,'--repo',repo]);
 try{const pages=await gh(`repos/${repo}/pages`);if(pages.build_type!=='workflow')await gh(`repos/${repo}/pages`,'PUT',{build_type:'workflow'});}catch(e){if(!e.message.includes('404'))throw e;await gh(`repos/${repo}/pages`,'POST',{build_type:'workflow'});}
 await gh(`repos/${repo}/actions/workflows/pages.yml/dispatches`,'POST',{ref:'main',inputs:{release_tag:tag}});
 step('等待 GitHub Pages 部署并核对线上版本');let verified=false,lastError='';for(let i=0;i<24;i++){try{const remote=JSON.parse(await remoteText(`${url}version.json?v=${Date.now()}`));if(remote.version===version.version&&remote.catalogHash===version.catalogHash){const raw=await remoteText(`${url}data/catalog.json?v=${Date.now()}`);if(hash(raw)!==version.catalogHash)throw new Error('公网目录哈希不匹配');const samples=db.records.filter(r=>!r.archived).filter((_,i)=>i===0||i===Math.floor(db.records.length/2)||i===db.records.length-1);for(const r of samples){const got=JSON.parse(await remoteText(`${url}data/records/${r.id}.json?v=${Date.now()}`));if(got.id!==r.id||got.title!==r.title)throw new Error('公网详情不匹配');}verified=true;break;}}catch(e){lastError=e.message;}await wait(10000);}
 if(!verified)throw new Error('本地构建与提交已完成，但公网尚未通过版本回读。'+lastError);
 const final={state:'公网已更新',url,version:version.version,verifiedAt:now(),catalogHash:version.catalogHash,audit};atomic(statusFile,final);console.log(JSON.stringify(final));
}catch(e){atomic(statusFile,{state:'发布失败',error:e.message,at:now(),localVersion:read().version});console.error(e);process.exitCode=1;}finally{if(descriptor!==undefined)fs.closeSync(descriptor);if(fs.existsSync(lock))fs.unlinkSync(lock);}
