import {createContext,useContext,useEffect,useLayoutEffect,useRef,useState}from'react';
import{ArrowUpRight,ArrowRight,BookOpen,Check,ChevronLeft,ChevronRight,Clock,FileText,Layers,Leaf,Menu,Plus,Search,Settings,Upload,Sun,RefreshCw,Link2,ExternalLink,Bookmark,Download,CheckCircle2,MoreHorizontal,X,PenLine,LoaderCircle,CalendarDays,Target,Home,CloudUpload,RotateCcw}from'lucide-react';
import ReactMarkdown from'react-markdown';import remarkGfm from'remark-gfm';
import * as api from'./api';import type{Catalog,RecordItem,Source,SourceRef}from'./types';import{kinds,subjects,today}from'./types';import{Editor}from'./Editor';import{Reader}from'./Reader';import{Growth}from'./Growth';
const menu=[['today','今日','DAILY',Home],['library','学习资料','LIBRARY',BookOpen],['review','三科复盘','REFLECTION',Target],['cards','卡片与速记','COLLECTION',Layers],['growth','向内生长','GROWTH',Leaf]] as const;
const scrolls=new Map<string,number>();
const searchStates=new Map<string,string>();
const pageLimits=new Map<string,number>();
function route(){const [pathname,q='']=location.hash.replace(/^#\/?/,'').split('?');return {path:pathname||'today',params:new URLSearchParams(q)};}
export function go(path:string,params:Record<string,string>={}){scrolls.set(location.hash,window.scrollY);const qs=new URLSearchParams(params).toString();location.hash=`/${path}${qs?'?'+qs:''}`;}
const CatalogContext=createContext<Catalog|null>(null);
export function Markdown({text}:{text:string}){const catalog=useContext(CatalogContext);return <div className="markdown"><ReactMarkdown remarkPlugins={[remarkGfm]} components={{a:({children,href})=>{const date=href?.match(/^(?:\.\/)?(\d{4}-\d{2}-\d{2})\.md(?:#.*)?$/)?.[1];const daily=date?catalog?.records.find(r=>r.kind==='article'&&r.topic==='每日精读'&&r.date===date):undefined;return daily?<a href={`#/record/${daily.id}`} onClick={e=>{if(!e.ctrlKey&&!e.metaKey&&!e.shiftKey&&!e.altKey){e.preventDefault();go(`record/${daily.id}`);}}}>{children}<ArrowUpRight size={12}/></a>:<a href={href} target="_blank" rel="noreferrer">{children}<ExternalLink size={12}/></a>;}}}>{text||'还没有正文。'}</ReactMarkdown></div>;}
export function Empty({title='这里还没有内容',text='从一条记录开始，让学习留下可以回看的痕迹。',action}:{title?:string;text?:string;action?:()=>void}){return <div className="empty"><BookOpen size={32} strokeWidth={1}/><h3>{title}</h3><p>{text}</p>{action&&<button className="button primary" onClick={action}><Plus size={16}/>新建记录</button>}</div>;}
function Tag({subject}:{subject:string}){return <span className={`tag ${subject}`}>{subjects[subject]||'综合'}</span>;}
function Botanical(){return <svg className="botanical" viewBox="0 0 300 260" fill="none" aria-hidden="true"><circle cx="175" cy="122" r="101" stroke="currentColor" opacity=".22"/><circle cx="175" cy="122" r="82" stroke="currentColor" opacity=".12"/><path d="M156 251C147 202 158 167 185 130C206 102 209 61 201 20M161 185C110 183 102 139 110 111C145 121 166 142 161 185ZM184 133C173 80 139 76 128 80C125 117 152 141 184 133ZM199 97C227 107 265 80 262 50C226 48 204 68 199 97ZM172 158C203 178 247 153 255 121C217 117 187 132 172 158ZM156 209C121 222 77 199 72 166C108 161 141 179 156 209Z" stroke="currentColor" strokeWidth="1.7"/><path d="M110 111L161 185M128 80L184 133M262 50L199 97M255 121L172 158M72 166L156 209" stroke="currentColor" strokeWidth=".8"/><circle cx="63" cy="87" r="3" fill="currentColor"/><path d="M49 103h20M59 93v20M232 204h13M238 198v13" stroke="currentColor"/><text x="40" y="239" fill="currentColor" fontSize="9" letterSpacing="4">GROW AT YOUR OWN PACE</text></svg>;}
export default function App(){
 const [catalog,setCatalog]=useState<Catalog|null>(null),[loadError,setLoadError]=useState(''),[current,setCurrent]=useState(route),[editor,setEditor]=useState<Partial<RecordItem>|null>(null),[toast,setToast]=useState(''),[mobileMenu,setMobileMenu]=useState(false),[search,setSearch]=useState(''),[searchIds,setSearchIds]=useState<string[]|null>(null),[searchReady,setSearchReady]=useState(false),[searchError,setSearchError]=useState('');
 const worker=useRef<Worker|null>(null),seq=useRef(0);const [limit,setLimit]=useState(24);
 const refresh=async()=>{api.invalidate();if(worker.current){worker.current.terminate();worker.current=null;setSearchReady(false);setSearchIds(null);}const data=await api.bootstrap();setCatalog(data);};
 useEffect(()=>{refresh().catch(e=>setLoadError(e.message));const change=()=>{setCurrent(route());setMobileMenu(false);setLimit(pageLimits.get(location.hash)||24);setSearch(searchStates.get(location.hash)||'');};window.addEventListener('hashchange',change);return()=>window.removeEventListener('hashchange',change);},[]);
 useEffect(()=>{if(!toast)return;const timer=setTimeout(()=>setToast(''),4500);return()=>clearTimeout(timer);},[toast]);
 useLayoutEffect(()=>{if(catalog)requestAnimationFrame(()=>window.scrollTo(0,scrolls.get(location.hash)||0));},[current.path,catalog!==null]);
 useEffect(()=>{if(!search.trim()||!catalog)return;if(worker.current)return;const w=new Worker(new URL('./search.worker.ts',import.meta.url),{type:'module'});worker.current=w;w.onmessage=e=>{if(e.data.seq===seq.current)setSearchIds(e.data.ids);};api.searchIndex().then(data=>{w.postMessage({type:'init',data});setSearchReady(true);}).catch(e=>{setSearchError(e.message);w.terminate();worker.current=null;});},[search,catalog]);
 useEffect(()=>{if(!search.trim()){setSearchIds(null);return;}if(!searchReady)return;const n=++seq.current;const timer=setTimeout(()=>worker.current?.postMessage({type:'query',query:search,seq:n}),120);return()=>clearTimeout(timer);},[search,searchReady]);
 useEffect(()=>()=>worker.current?.terminate(),[]);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if((e.ctrlKey||e.metaKey)&&e.key==='k'){e.preventDefault();document.getElementById('global-search')?.focus();}if(e.key==='Escape')setMobileMenu(false);};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[]);
 if(loadError)return <div className="boot"><Leaf/><h1>暂时没能打开书桌</h1><p>{loadError}</p><button className="button primary" onClick={()=>location.reload()}>重新加载</button></div>;
 if(!catalog)return <div className="boot"><Leaf className="spin"/><p>正在打开你的学习书桌…</p></div>;
 const local=api.isLocal(),[page,id]=current.path.split('/'),params=current.params;const active=['record','source'].includes(page)?'library':page;const selectedSubject=params.get('subject')||'',selectedKind=params.get('kind')||'';
 const create=(kind='note',extras:Partial<RecordItem>={})=>setEditor({kind,subject:selectedSubject||'xingce',...extras});
 const notify=(m:string)=>setToast(m);
 const saved=async(r:RecordItem)=>{setEditor(null);await refresh();notify('已保存到电脑');go(`record/${r.id}`);};
 const openRecord=(r:RecordItem)=>{searchStates.set(location.hash,search);pageLimits.set(location.hash,limit);setSearch('');localStorage.setItem('growth-last-read',r.id);go(`record/${r.id}`,{from:current.path});};
 const due=catalog.records.filter(r=>r.nextReview&&r.nextReview<=today());
 const filtered=catalog.records.filter(r=>(!selectedSubject||r.subject===selectedSubject)&&(!selectedKind||r.kind===selectedKind)&&(!params.has('due')||due.includes(r))).sort((a,b)=>(b.date||'').localeCompare(a.date||''));
 const list=(rows:RecordItem[],empty?:string)=><>{rows.length?<div className="record-grid">{rows.slice(0,limit).map(r=><RecordCard key={r.id} item={r} onOpen={()=>openRecord(r)}/>)}</div>:<Empty title={empty} action={local?()=>create():undefined}/>} {rows.length>limit&&<button className="button load-more" onClick={()=>{setLimit(limit+24);pageLimits.set(location.hash,limit+24);}}>再看 24 条 <ChevronRight size={16}/></button>}</>;
 const filters=(withKinds?:string[])=> <div className="filter-bar"><div className="tabs"><button className={!selectedSubject?'tab active':'tab'} onClick={()=>go(page,{...(selectedKind?{kind:selectedKind}:{}),...(params.has('due')?{due:'1'}:{})})}>全部</button>{Object.entries(subjects).filter(([k])=>page==='growth'||k!=='growth').map(([k,v])=><button key={k} className={selectedSubject===k?'tab active':'tab'} onClick={()=>go(page,{subject:k,...(selectedKind?{kind:selectedKind}:{}),...(params.has('due')?{due:'1'}:{})})}>{v}</button>)}</div>{withKinds&&<select aria-label="记录类型筛选" value={selectedKind} onChange={e=>go(page,{...(selectedSubject?{subject:selectedSubject}:{}),...(e.target.value?{kind:e.target.value}:{}),...(params.has('due')?{due:'1'}:{})})}><option value="">全部类型</option>{withKinds.map(k=><option value={k} key={k}>{kinds[k]}</option>)}</select>}</div>;
 return <CatalogContext.Provider value={catalog}><div className="app-shell">
 <a href="#main-content" className="skip-link" onClick={e=>{e.preventDefault();document.getElementById('main-content')?.focus();}}>跳到主要内容</a>
 <aside className={`sidebar ${mobileMenu?'open':''}`}><a className="brand" href="#/today"><span className="brand-icon"><Leaf size={24} strokeWidth={1.4}/></span><span><strong>向内生长</strong><small>学习与复盘 · EST. 2026</small></span></a><div className="sidebar-label">我的学习空间</div><nav>{menu.map(([key,label,en,Icon],i)=><button key={key} className={`nav-item ${active===key?'active':''}`} onClick={()=>{setSearch('');go(key);}}><Icon size={19} strokeWidth={1.5}/><span>{label}</span><small>0{i+1}</small></button>)}</nav><div className="sidebar-note"><span className="eyebrow">A LITTLE, EVERY DAY</span><p>学到的，慢慢消化。<br/>走过的，认真留下。</p><div className="tiny-line"/><span>每一次回看，都是新的生长。</span></div><div className="sidebar-bottom"><button className="nav-item" onClick={()=>{setSearch('');go('settings');}}><Settings size={18}/><span>{local?'设置与发布':'关于与更新'}</span></button><div className="mode"><span className={`status-dot ${local?'local':''}`}/>{local?'电脑管理版':'公开阅读版'}<small>{local?'本地保存':'自由阅读'}</small></div></div></aside>
 {mobileMenu&&<div className="sidebar-scrim" onClick={()=>setMobileMenu(false)}/>}
 <div className="main-shell"><header className="topbar"><button className="icon-button mobile-menu" aria-label="打开导航" onClick={()=>setMobileMenu(!mobileMenu)}><Menu size={21}/></button><div className="breadcrumb">我的空间 <span>/</span> {menu.find(m=>m[0]===active)?.[1]||'内容详情'}</div><label className="search-box"><Search size={17}/><input id="global-search" value={search} onChange={e=>{setSearch(e.target.value);setLimit(24);}} placeholder="搜索资料、卡片与复盘" aria-label="全站搜索"/>{search?<button className="icon-button" onClick={()=>setSearch('')} aria-label="清除搜索"><X size={14}/></button>:<kbd>Ctrl K</kbd>}</label>{local&&<button className="button dark quick-add" onClick={()=>create()}><Plus size={16}/><span>随手记</span></button>}<span className="avatar">生</span></header>
 <main id="main-content" className={`content ${page==='record'?'detail-content':''}`} tabIndex={-1}>
 {search.trim()?<><PageHead eyebrow="FIND YOUR CONNECTIONS" title="找到，连起来。" description={`在 ${catalog.records.length} 条内容中搜索「${search}」`}/>{searchError&&<p className="error-message">{searchError}</p>}{!searchReady?<p className="inline-status"><LoaderCircle className="spin" size={16}/>首次加载全文索引…</p>:list(catalog.records.filter(r=>searchIds?.includes(r.id)),'没有找到相关内容')}</>:
 page==='today'?<>
  <div className="today-heading"><div><span className="eyebrow">YOUR DAILY EDITION</span><h1>把今天学到的，<em>留给明天。</em></h1></div><div className="date-stamp"><span>{today().slice(0,4)} / {today().slice(5,7)}</span><strong>{today().slice(8)}</strong><small>{new Intl.DateTimeFormat('zh-CN',{weekday:'long'}).format(new Date())}</small></div></div>
  <section className="hero"><div className="hero-copy"><span className="pill"><span className="status-dot"/>持续积累，循序生长</span><h2>让知识有来处，<br/>让进步有迹可循。</h2><p>从一份资料，到一次理解，再到真正掌握。<br/>你的学习、思考与复盘，都在这里慢慢连起来。</p><button className="button primary" onClick={()=>{const last=catalog.records.find(r=>r.id===localStorage.getItem('growth-last-read'));last?openRecord(last):go('library');}}>继续学习 <ArrowUpRight size={17}/></button><button className="hero-secondary" onClick={()=>go('review')}>看看我的复盘 <ArrowRight size={15}/></button></div><Botanical/><span className="hero-index">CHAPTER 01 / EVERYDAY GROWTH</span></section>
  <div className="stats-strip"><Stat number={catalog.sources.length} label="份原始资料" icon={<BookOpen/>}/><Stat number={catalog.records.filter(r=>['knowledge','memory','quote','common'].includes(r.kind)).length} label="张知识与速记卡" icon={<Layers/>}/><Stat number={catalog.records.filter(r=>['review','growth','weekly','error'].includes(r.kind)).length} label="次学习与成长复盘" icon={<PenLine/>}/><Stat number={due.length} label="张卡片待复习" icon={<RefreshCw/>}/></div>
  <div className="dashboard-columns"><div><SectionHead eyebrow="PICK UP WHERE YOU LEFT OFF" title="回到学习现场" action="全部资料" onAction={()=>go('library')}/><div className="featured-sources">{catalog.sources.slice(0,3).map((s,i)=><button className="source-row" key={s.id} onClick={()=>go(`source/${s.id}`)}><span className={`book-cover cover-${i}`}><small>{subjects[s.subject]||'学习'}</small><BookOpen size={24} strokeWidth={1}/><span>{String(i+1).padStart(2,'0')}</span></span><span className="source-row-content"><Tag subject={s.subject}/><h3>{s.title}</h3><p>{s.topic} <span>·</span> {s.pageCount} 页</p></span><ArrowUpRight size={19}/></button>)}</div></div><aside className="daily-aside"><SectionHead eyebrow="A SMALL STEP" title="今天，温习一点"/><div className="review-callout"><div className="callout-top"><RefreshCw size={22} strokeWidth={1.5}/><span>{due.length} 张待复习</span></div><h3>{due.length?'让模糊的，再清楚一点。':'没有到期任务，按自己的节奏。'}</h3><p>{due.length?'重逢一次知识，比匆忙看过十次更有意义。':'可以从缓冲中的知识卡挑选一张，开始复习。'}</p><button className="button outline full" onClick={()=>go('cards',due.length?{due:'1'}:{kind:'knowledge'})}>{due.length?'开始今日复习':'挑一张学习卡'}<ArrowRight size={15}/></button></div><button className="quick-note-tile" onClick={()=>local?create():go('cards',{kind:'note'})}><PenLine size={22} strokeWidth={1.4}/><span><strong>灵感，先记下来。</strong><small>{local?'不必完整，一句话也可以。':'看看那些被认真留下的想法。'}</small></span><Plus size={18}/></button></aside></div>
  <SectionHead eyebrow="RECENTLY ADDED" title="新近收获" action="浏览全部卡片" onAction={()=>go('cards')}/><div className="record-grid three">{[...catalog.records].filter(r=>['knowledge','quote','note','common'].includes(r.kind)).sort((a,b)=>b.date.localeCompare(a.date)).slice(0,3).map(r=><RecordCard key={r.id} item={r} onOpen={()=>openRecord(r)}/>)}</div>
  <footer className="page-footer"><span>不急着成为谁，先慢慢长成自己。</span><Leaf size={16}/><span>向内生长 / GROW WITHIN</span></footer>
 </>:
 page==='library'?<><PageHead eyebrow="THE LEARNING LIBRARY" title="每一份资料，都有下一步。" description="原始讲义、申论精读与常识积累，在同一个书架上。" action={local?()=>go('upload'):undefined} actionLabel="上传资料"/>{filters(['article','quote','common'])}{!selectedKind&&<><SectionHead title="原始资料" eyebrow="SOURCE MATERIALS"/><div className="source-grid">{catalog.sources.filter(s=>!selectedSubject||s.subject===selectedSubject).map((s,i)=><SourceCard key={s.id} source={s} index={i} onOpen={()=>go(`source/${s.id}`)}/>)}</div></>}<SectionHead title={selectedKind?kinds[selectedKind]:'阅读与积累'} eyebrow="READ & CONNECT"/>{list(filtered.filter(r=>['article','quote','common'].includes(r.kind)))}</>:
 page==='cards'?<><PageHead eyebrow="KNOWLEDGE, IN YOUR OWN WORDS" title={params.has('due')?'今天，让记忆更牢一点。':'把理解，收进一张卡片。'} description="学习卡理清知识，复盘卡留下方法，速记卡帮助记忆，随手记接住灵感。" action={local?()=>create(selectedKind||'knowledge'):undefined} actionLabel="新建卡片"/>{filters(['knowledge','review','memory','note','quote','common'])}{params.has('due')&&<div className="notice">仅显示截至今天到期的卡片。<button className="text-button" onClick={()=>go('cards')}>查看全部</button></div>}{list(filtered.filter(r=>['knowledge','review','memory','note','quote','common'].includes(r.kind)))}</>:
 page==='review'?<><PageHead eyebrow="REFLECT, THEN MOVE FORWARD" title="看清走过的，走好下一步。" description="行测、申论、公安：从真实记录里，找到需要巩固的地方。" action={local?()=>create('review'):undefined} actionLabel="写一篇复盘"/>{filters(['review','error','practice','weekly'])}<div className="subject-overview">{Object.entries(subjects).filter(([s])=>s!=='growth').map(([s,title])=>{const r=catalog.records.filter(r=>r.subject===s);return <button key={s} className={`subject-panel ${s}`} onClick={()=>go('review',{subject:s})}><span className="eyebrow">{s.toUpperCase()}</span><h2>{title}</h2><p>{r.filter(x=>x.kind==='knowledge').length} 张知识卡 · {r.filter(x=>['review','error'].includes(x.kind)).length} 次复盘</p><ArrowUpRight size={19}/></button>;})}</div><SectionHead eyebrow="YOUR KNOWLEDGE MAP" title="知识地图"/><div className="topic-map">{Object.entries(catalog.records.filter(r=>(!selectedSubject||r.subject===selectedSubject)&&r.subject!=='growth'&&['knowledge','review','error'].includes(r.kind)).reduce((a:Record<string,RecordItem[]>,r)=>{const key=r.topic||'待归类';(a[key]??=[]).push(r);return a;},{})).slice(0,30).map(([topic,rows])=><button key={topic} onClick={()=>setSearch(topic)}><span>{topic}</span><small>{rows.length} 条 · {rows.some(r=>r.kind==='error')?'有错待稳':rows.some(r=>r.nextReview)?'复习中':'学习中'}</small></button>)}</div><SectionHead eyebrow="REFLECTION JOURNAL" title="复盘记录"/>{list(filtered.filter(r=>['review','error','practice','weekly'].includes(r.kind)&&r.subject!=='growth'))}</>:
 page==='growth'?<Growth catalog={catalog} onOpen={openRecord} onCreate={create} notify={notify} refresh={refresh} tab={params.get('tab')||'journal'}/>:
 page==='record'?<RecordDetail key={id} id={id} catalog={catalog} onEdit={setEditor} onCreate={create} notify={notify} refresh={refresh} params={params}/>:
 page==='source'?<SourcePage key={id} id={id} catalog={catalog} page={Number(params.get('page'))||1} onCreate={create} onOpen={openRecord}/>:
 page==='upload'?<UploadPage refresh={refresh} notify={notify}/>:
 page==='settings'?<SettingsPage catalog={catalog} refresh={refresh} notify={notify}/>:<Empty title="这个页面不存在" text="请从左侧导航重新进入。"/>}
 </main></div>
 <nav className="mobile-nav">{menu.map(([key,label,,Icon])=><button key={key} className={active===key?'active':''} onClick={()=>{setSearch('');go(key);}}><Icon size={20}/><span>{label==='卡片与速记'?'卡片':label==='向内生长'?'成长':label==='学习资料'?'资料':label==='三科复盘'?'复盘':label}</span></button>)}</nav>
 {editor&&<Editor key={editor.id||'new'} initial={editor} catalog={catalog} onClose={()=>setEditor(null)} onSaved={saved}/>}{toast&&<div className="toast" role="status"><CheckCircle2 size={18}/>{toast}</div>}
 </div></CatalogContext.Provider>;
}
function PageHead({eyebrow,title,description,action,actionLabel}:{eyebrow:string;title:string;description?:string;action?:()=>void;actionLabel?:string}){return <div className="page-head"><div><span className="eyebrow">{eyebrow}</span><h1>{title}</h1>{description&&<p>{description}</p>}</div>{action&&<button className="button primary" onClick={action}><Plus size={16}/>{actionLabel||'新增'}</button>}</div>;}
function SectionHead({title,eyebrow,action,onAction}:{title:string;eyebrow?:string;action?:string;onAction?:()=>void}){return <div className="section-head"><div>{eyebrow&&<span className="eyebrow">{eyebrow}</span>}<h2>{title}</h2></div>{action&&<button className="text-link" onClick={onAction}>{action}<ArrowUpRight size={16}/></button>}</div>;}
function Stat({number,label,icon}:{number:number;label:string;icon:React.ReactNode}){return <div className="stat"><div>{icon}<span>{label}</span></div><strong>{String(number).padStart(2,'0')}</strong></div>;}
function RecordCard({item:r,onOpen}:{item:RecordItem;onOpen:()=>void}){return <button className={`record-card kind-${r.kind}`} onClick={onOpen}><div className="card-top"><span className="card-kind"><span className="kind-dot"/>{kinds[r.kind]}</span><span className="card-date">{r.date?.slice(5)}</span></div><h3>{r.title}</h3><p>{r.excerpt||r.body?.slice(0,140)||'打开看看这条记录。'}</p><div className="card-bottom"><Tag subject={r.subject}/><span>{r.sourceRefs?.some(s=>s.sourceId)?'可定位原页':r.topic||'展开阅读'}</span><ArrowUpRight size={16}/></div></button>;}
function SourceCard({source:s,index,onOpen}:{source:Source;index:number;onOpen:()=>void}){return <button className="source-card" onClick={onOpen}><div className={`source-art cover-${index%3}`}><span>{s.kind==='pdf'?'PDF DOCUMENT':'ORIGINAL IMAGE'}</span><BookOpen size={42} strokeWidth={.8}/><small>{String(index+1).padStart(2,'0')}</small></div><div className="source-card-body"><Tag subject={s.subject}/><h3>{s.title}</h3><p>{s.pageCount} 页 <span>·</span> {(s.size/1024/1024).toFixed(1)} MB {s.missing?'· 原文件缺失':''}</p><ArrowUpRight size={17}/></div></button>;}
function RecordDetail({id,catalog,onEdit,onCreate,notify,refresh,params}:{id:string;catalog:Catalog;onEdit:(r:Partial<RecordItem>)=>void;onCreate:(kind:string,extras?:Partial<RecordItem>)=>void;notify:(s:string)=>void;refresh:()=>Promise<void>;params:URLSearchParams}){
 const [r,setR]=useState<RecordItem|null>(null),[error,setError]=useState(''),[reference,setReference]=useState<SourceRef|null>(null),[reveal,setReveal]=useState(false),[refDirty,setRefDirty]=useState(false),[busy,setBusy]=useState(false),[refIndex,setRefIndex]=useState(0);
 useEffect(()=>{api.record(id).then(row=>{setR(row);const n=Number(params.get('ref')||0),ref=row.sourceRefs?.[n];if(ref?.sourceId){setReference({...ref,...params.get('page')?{page:Number(params.get('page'))}:{}});setRefIndex(n);}}).catch(e=>setError(e.message));},[id]);
 const mutation=async(action:()=>Promise<RecordItem>)=>{setBusy(true);try{const row=await action();setR(row);await refresh();notify('已保存到电脑');}catch(e:any){setError(e.message);}finally{setBusy(false);}};
 if(error&&!r)return <Empty title={error}/>;if(!r)return <p className="inline-status"><LoaderCircle className="spin"/>正在打开记录…</p>;
 const source=reference?.sourceId?catalog.sources.find(s=>s.id===reference.sourceId):null;const related=catalog.records.filter(x=>x.id!==r.id&&((r.links||[]).includes(x.id)||(x.links||[]).includes(r.id)||x.sourceRefs?.some(a=>r.sourceRefs?.some(b=>a.sourceId&&a.sourceId===b.sourceId))));
 const openRef=(ref:SourceRef,i:number)=>{setReference(ref);setRefIndex(i);setRefDirty(false);history.replaceState(null,'',`#/${'record/'+r.id}?ref=${i}&page=${ref.page||1}`);};
 const saveRef=()=>mutation(async()=>{const refs=[...r.sourceRefs];if(refIndex<0){refs.push(reference!);setRefIndex(refs.length-1);}else refs[refIndex]=reference!;const row=await api.post('records',{record:{...r,sourceRefs:refs},revision:r.revision});setRefDirty(false);return row;});
 return <><div className="detail-nav"><button className="text-link" onClick={()=>{if(refDirty&&!confirm('来源标注尚未保存，确定离开？'))return;history.length>1?history.back():go(params.get('from')||'cards');}}><ChevronLeft size={17}/>返回列表</button><div><button className="text-link" onClick={()=>{navigator.clipboard.writeText(api.isLocal()?'https://pf11223333.github.io/growth-study-platform/'+location.hash:location.href).then(()=>notify(api.isLocal()?'已复制阅读链接，发布后即可访问':'已复制此页链接')).catch(()=>notify('请复制浏览器地址栏链接'));}}><Link2 size={15}/>复制链接</button>{api.isLocal()&&<button className="button outline small" onClick={()=>onEdit(r)}><PenLine size={14}/>编辑</button>}</div></div>
 <div className={`detail-layout ${source?'with-reader':''}`}><article className="reading-article"><div className="article-meta"><Tag subject={r.subject}/><span>{kinds[r.kind]}</span><span>{r.date}</span></div><h1>{r.title}</h1><div className="article-subtitle">{r.topic}{r.verificationStatus&&<span> · {r.verificationStatus}</span>}</div>
 {r.kind==='fortune'&&<div className="notice">仅供娱乐与自我观察，不作为学习表现或现实决策依据。</div>}
 {r.kind==='memory'&&!reveal?<div className="answer-cover"><BookOpen size={26}/><p>先在心里回答，再翻开答案。</p><button className="button primary" onClick={()=>setReveal(true)}>查看答案</button></div>:<><Markdown text={r.body||''}/>{r.kind==='memory'&&<button className="chip" onClick={()=>setReveal(false)}>遮住答案，重新自测</button>}</>}
 {r.details&&<details className="raw-details"><summary>更多笔记与来源说明</summary><Structured value={r.details}/></details>}
 <section className="sources-section"><span className="eyebrow">BACK TO THE SOURCE</span><h3>知识的来处</h3>{r.sourceRefs?.length?r.sourceRefs.map((ref,i)=><div key={i} className="source-link">{ref.sourceId?<button onClick={()=>openRef(ref,i)}><FileText size={17}/><span>{catalog.sources.find(s=>s.id===ref.sourceId)?.title||ref.label||'原资料'}<small>第 {ref.page||1} 页 · {ref.regions?.length?`${ref.regions.length} 处标注`:'待补标'}</small></span><ArrowUpRight size={17}/></button>:<a href={ref.url} target="_blank" rel="noreferrer"><ExternalLink size={16}/><span>{ref.label||ref.url}</span><ArrowUpRight size={16}/></a>}</div>):<p className="muted">这条记录尚未关联原资料。{api.isLocal()?'可通过编辑补充。':''}</p>}</section>
 {api.isLocal()&&<section className="study-actions"><h3>让这次理解，走得更远。</h3><div className="button-row"><button className="button outline" onClick={()=>onCreate('review',{title:`复盘 · ${r.title}`,subject:r.subject,topic:r.topic,sourceRefs:r.sourceRefs,links:[r.id],body:'## 实际表现\n\n## 原因\n\n## 纠正方法\n\n## 下一步行动\n'})}>写关联复盘</button><button className="button outline" onClick={()=>onCreate(r.kind==='note'?'knowledge':'memory',{title:r.title,body:r.body,subject:r.subject,topic:r.topic,sourceRefs:r.sourceRefs,links:[r.id]})}>{r.kind==='note'?'整理为学习卡':'制作速记卡'}</button><button className="chip" onClick={()=>mutation(()=>api.post('records',{record:{...r,starred:!r.starred},revision:r.revision}))}><Bookmark size={14}/>{r.starred?'取消标星':'标星'}</button></div>{['knowledge','memory','quote','common','review'].includes(r.kind)&&<><p>今天记住了多少？{r.nextReview?` 下次复习：${r.nextReview}`:'选择一次评价，开始间隔复习。'}</p><div className="rating-buttons">{['忘记','模糊','掌握'].map(v=><button key={v} disabled={busy} onClick={()=>mutation(()=>api.post('review',{id:r.id,revision:r.revision,rating:v}))}>{v}</button>)}</div></>}</section>}
 {r.reviewHistory?.length&&<details><summary>复习历史（{r.reviewHistory.length}）</summary>{r.reviewHistory.map((h,i)=><p key={i}>{h.at.slice(0,10)} · {h.rating}</p>)}</details>}
 {related.length>0&&<section className="related-section"><span className="eyebrow">CONNECTED LEARNING</span><h3>继续连起来</h3>{related.slice(0,16).map(x=><button key={x.id} onClick={()=>go(`record/${x.id}`)}><span>{kinds[x.kind]}</span>{x.title}<ArrowUpRight size={16}/></button>)}</section>}
 {api.isLocal()&&<button className="text-button archive-action" onClick={()=>{if(confirm('归档这条记录？历史和原资料会保留。'))mutation(async()=>{const row=await api.post('records',{record:{...r,archived:true},revision:r.revision});go('cards');return row;});}}>归档记录</button>}{error&&<p className="error-message">{error}</p>}
 </article>{source&&reference&&<aside className="reader-pane">{refDirty&&<div className="save-annotation"><span>标注尚未保存</span><button className="button primary small" disabled={busy} onClick={saveRef}>保存来源标注</button></div>}<Reader key={source.id} source={source} reference={reference} onRefChange={ref=>{if(ref.page!==reference.page){const index=r.sourceRefs.findIndex(x=>x.sourceId===ref.sourceId&&x.page===ref.page);setRefIndex(index);setReference(index>=0?r.sourceRefs[index]:ref);setRefDirty(false);}else{setReference(ref);setRefDirty(api.isLocal());}}} onCreate={api.isLocal()?ref=>onCreate('knowledge',{sourceRefs:[ref],subject:source.subject,topic:source.topic,links:[r.id]}):undefined} onClose={()=>{if(!refDirty||confirm('标注尚未保存，确定关闭？'))setReference(null);}}/></aside>}</div></>;
}
function SourcePage({id,catalog,page,onCreate,onOpen}:{id:string;catalog:Catalog;page:number;onCreate:(k:string,e:Partial<RecordItem>)=>void;onOpen:(r:RecordItem)=>void}){const s=catalog.sources.find(s=>s.id===id);const [ref,setRef]=useState<SourceRef>({sourceId:id,page,regions:[]});if(!s)return <Empty title="资料不存在"/>;const related=catalog.records.filter(r=>r.sourceRefs?.some(r=>r.sourceId===id));return <><div className="detail-nav"><button className="text-link" onClick={()=>go('library')}><ChevronLeft size={17}/>返回资料库</button><span className="muted">{related.length} 条关联记录</span></div><div className="source-workspace"><Reader source={s} reference={ref} onRefChange={r=>{setRef(r);history.replaceState(null,'',`#/source/${id}?page=${r.page||1}`);}} onCreate={api.isLocal()?r=>onCreate('knowledge',{sourceRefs:[r],subject:s.subject,topic:s.topic}):undefined}/><aside className="source-context"><span className="eyebrow">READ → UNDERSTAND → REFLECT</span><h2>从这里，展开学习。</h2><p>原资料与自己的理解放在一起，随时核对，慢慢消化。</p>{api.isLocal()&&<button className="button primary" onClick={()=>onCreate('knowledge',{sourceRefs:[ref],subject:s.subject,topic:s.topic})}><Plus size={16}/>从当前页建卡</button>}<SectionHead title="关联卡片与复盘"/>{related.length?related.map(r=><button className="context-record" onClick={()=>onOpen(r)} key={r.id}><span>{kinds[r.kind]}</span><h3>{r.title}</h3><small>第 {r.sourceRefs.find(x=>x.sourceId===id)?.page||1} 页 <ArrowUpRight size={14}/></small></button>):<p className="muted">尚未关联卡片，阅读时可以从原页直接建卡。</p>}</aside></div></>;}
function UploadPage({refresh,notify}:{refresh:()=>Promise<void>;notify:(s:string)=>void}){const [file,setFile]=useState<File|null>(null),[subject,setSubject]=useState('xingce'),[topic,setTopic]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');if(!api.isLocal())return <Empty title="请在电脑本地管理版上传"/>;const upload=async()=>{if(!file)return;setBusy(true);try{const bytes=new Uint8Array(await file.arrayBuffer());let binary='';for(let i=0;i<bytes.length;i+=32768)binary+=String.fromCharCode(...bytes.subarray(i,i+32768));const r=await api.post('upload',{filename:file.name,base64:btoa(binary),subject,topic});await refresh();notify(r.duplicate?'这份资料已存在，已为你定位':'原文件与预览已保存');go(`source/${r.source.id}`);}catch(e:any){setError(e.message);}finally{setBusy(false);}};return <><PageHead eyebrow="A NEW BEGINNING" title="把资料放上书架。" description="上传 PDF、截图或笔记图片，保留完整原文件，自动生成逐页预览。"/><section className="upload-panel"><label className="drop-zone"><Upload size={34} strokeWidth={1.2}/><h3>{file?file.name:'选择一份学习资料'}</h3><p>PDF / PNG / JPG / WebP · 最大 140 MB</p><input type="file" accept=".pdf,.png,.jpg,.jpeg,.webp" onChange={e=>setFile(e.target.files?.[0]||null)}/></label><div className="form-row"><label>学科<select value={subject} onChange={e=>setSubject(e.target.value)}>{Object.entries(subjects).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label>主题<input value={topic} onChange={e=>setTopic(e.target.value)} placeholder="这份资料讲的是什么？"/></label></div>{error&&<p className="error-message">{error}</p>}<button className="button primary" disabled={!file||busy} onClick={upload}>{busy?<LoaderCircle size={16} className="spin"/>:<Upload size={16}/>} {busy?'保存原文件并生成预览…':'上传并打开'}</button><p className="muted">大 PDF 生成预览需要一些时间，完成前请保留此页面。</p></section></>;}
const fieldLabels:Record<string,string>={trigger:'题干信号',sourceUrl:'原始网址',verifiedAt:'核验日期',effectiveDate:'施行日期',sourceType:'来源类别',verificationStatus:'核验状态',examPatterns:'常见题型',difficulty:'难度',examValue:'考点重要性',mastery:'掌握情况',priority:'优先级',starLevel:'星级',activationStatus:'复习启用状态',reviewStatus:'复习状态',nextReview:'下次复习',reviewStage:'复习阶段',reviewCount:'复习次数',stabilizedAt:'稳定掌握日期',canonicalModule:'分类模块',canonicalTopic:'分类主题',needsClassification:'待归类',module:'模块',topic:'主题',subject:'学科',tags:'标签',recordType:'记录类型',durationMinutes:'学习分钟数',practice:'练习表现',attachments:'原始附件',originalName:'文件名',uploadId:'来源编号',pageNumber:'原始页码',label:'来源说明',quote:'原文摘录',createdDate:'写信日期',deliverDate:'送达日期',updatedDate:'更新日期',questionType:'题型',questionId:'题目编号',userAnswer:'我的作答',correctAnswer:'正确答案',checkIn:'状态自评',metrics:'记录指标',emotionInsight:'情绪觉察',mentorStatus:'导师分析状态',sourceContent:'原始内容',aiContent:'AI 整理',sourceRefs:'来源',originalPdf:'原始文件',originalPage:'原始页码',courseExcerpt:'课程摘录',rawAndAiSeparated:'来源与 AI 已分层',generatedBy:'整理工具',generatedAt:'整理时间',explanation:'解释',uncertainty:'不确定项',summary:'摘要',story:'当天记录',learning:'学习收获',mentorNotes:'导师记录',ifThen:'行动约定',checklist:'行动清单',wins:'今天做成',feelings:'感受',thoughts:'想法',title:'标题',text:'内容',date:'日期',message:'留言',reply:'回复',rule:'知识规则',method:'方法',exception:'例外',memory:'记忆',pitfalls:'易混点',easyExample:'例子',storyMemory:'场景记忆',nodes:'知识节点',quiz:'自测',question:'问题',options:'选项',answer:'答案',reason:'原因',confidence:'置信度',verificationNote:'核验说明',keyPoints:'要点',actions:'行动',uncertainties:'待确认',miniQuiz:'自测',source:'来源',status:'状态'};
export function Structured({value,depth=0}:{value:any;depth?:number}){if(value===null||value===undefined||value==='')return null;if(typeof value==='boolean')return <span>{value?'是':'否'}</span>;if(typeof value!=='object')return <p className="preserve">{String(value)}</p>;if(depth>5)return <p>内容层级较深，请在本地备份中查看完整结构。</p>;if(Array.isArray(value))return <div className="structured-list">{value.map((v,i)=><div key={i}><Structured value={v} depth={depth+1}/></div>)}</div>;return <dl className="structured">{Object.entries(value).filter(([k,v])=>v!==null&&v!==''&&!/^(?:id|importKey|contentFingerprint|moduleId|topicId|sourceDocumentKey|captureId|createdAt|updatedAt|importedAt|sha256|originalFileSha256)$/.test(k)).map(([k,v])=><div key={k}><dt>{fieldLabels[k]||k}</dt><dd><Structured value={v} depth={depth+1}/></dd></div>)}</dl>;}
function SettingsPage({catalog,refresh,notify}:{catalog:Catalog;refresh:()=>Promise<void>;notify:(s:string)=>void}){const [status,setStatus]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState('');const load=()=>api.getJSON('/api/status').then(setStatus);useEffect(()=>{if(!api.isLocal())return;load().catch(e=>setError(e.message));const t=setInterval(()=>load().catch(()=>{}),5000);return()=>clearInterval(t);},[]);const act=async(name:string,data:any={},message='已完成')=>{setBusy(name);setError('');try{await api.post(name,data);await refresh();await load();notify(message);}catch(e:any){setError(e.message);}finally{setBusy('');}};return <><PageHead eyebrow="YOUR SPACE, WELL KEPT" title={api.isLocal()?'整理好，也分享好。':'关于这间学习书房。'} description={`当前内容版本 ${catalog.version} · 更新于 ${new Date(catalog.updatedAt).toLocaleString('zh-CN')}`}/><div className="settings-grid"><section className="settings-panel"><span className="eyebrow">PUBLIC EDITION</span><h2>公开阅读版</h2><p>学习资料和复盘公开可读。正式编辑与复习记录在电脑管理版完成，发布后其他设备可看到更新。</p><a className="text-link" href="https://pf11223333.github.io/growth-study-platform/" target="_blank" rel="noreferrer">打开分享链接 <ExternalLink size={15}/></a>{api.isLocal()&&<><div className={`publication-state ${status?.publication?.state==='公网已更新'?'success':''}`}><span className="status-dot"/><strong>{status?.publication?.state||'尚未发布'}</strong><p>{status?.publication?.step||status?.publication?.error||''}</p>{status?.publication?.version&&<small>线上版本 {status.publication.version}</small>}</div><button className="button primary" disabled={!!busy||status?.publication?.state==='发布中'} onClick={()=>act('publish',{},'已开始发布，可在这里查看结果')}><CloudUpload size={17}/>一键发布</button><p className="muted">先核验本地数据和资料，再发布并独立回读公网。</p></>}</section>
 {api.isLocal()&&<><section className="settings-panel"><span className="eyebrow">KEEP EVERYTHING CONNECTED</span><h2>接入旧站的新内容</h2><p>增量导入旧网站和每日自动化产生的资料。新平台已编辑的内容保留本地版本，冲突单独列出。</p><button className="button outline" disabled={!!busy} onClick={()=>act('import',{},'增量导入完成')}><RefreshCw size={16} className={busy==='import'?'spin':''}/>检查并导入</button><p className="muted">已发现 {status?.conflicts?.length||0} 项待处理冲突</p></section><section className="settings-panel"><span className="eyebrow">A SAFE WAY BACK</span><h2>备份与恢复</h2><p>快照保存结构化记录与来源关系，原文件独立保留。完整迁移电脑请复制整个 data 目录。</p><button className="button outline" disabled={!!busy} onClick={()=>act('backup',{},'快照已保存')}><Download size={16}/>创建快照</button><details><summary>恢复历史快照</summary>{status?.backups?.map((name:string)=><div className="backup-row" key={name}><span>{name.replace('snapshot-','').slice(0,19)}</span><button className="text-button" disabled={!!busy} onClick={()=>{if(confirm('将恢复这份快照；当前数据会先自动备份。'))act('restore',{name},'已恢复快照');}}>恢复</button></div>)}</details></section></>}
 <section className="settings-panel"><span className="eyebrow">BUILT FOR EVERYDAY LEARNING</span><h2>让每次学习，都有回响。</h2><p>三科复盘、申论积累与向内生长，保留各自清晰的空间，也让资料与理解彼此相连。</p><p className="muted">向内生长 · 学习与复盘 / 1.0</p></section></div>{error&&<p className="error-message" role="alert">{error}</p>}{status?.conflicts?.map((c:any)=><section className="settings-panel conflict-panel" key={c.id}><h3>导入冲突：{c.incoming.title}</h3><details><summary>查看新导入版本</summary><Markdown text={c.incoming.body}/></details><div className="button-row"><button className="button outline" onClick={()=>act('conflict',{id:c.id,choice:'local'})}>保留本地编辑</button><button className="button outline" onClick={()=>act('conflict',{id:c.id,choice:'incoming'})}>采用新导入版本</button></div></section>)}</>;}
