import {useEffect,useState}from'react';import{X,Save,Link2,LoaderCircle}from'lucide-react';import type{Catalog,RecordItem,SourceRef}from'./types';import{kinds,subjects,today}from'./types';import{post}from'./api';
export function Editor({initial,catalog,onClose,onSaved}:{initial:Partial<RecordItem>;catalog:Catalog;onClose:()=>void;onSaved:(r:RecordItem)=>void}){
 const [form,setForm]=useState<any>({title:'',body:'',kind:'note',subject:'xingce',topic:'',date:today(),tags:[],sourceRefs:[],links:[],...initial}),[error,setError]=useState(''),[saving,setSaving]=useState(false),[relation,setRelation]=useState(''),[dirty,setDirty]=useState(false);
 const update=(k:string,v:any)=>{setForm((f:any)=>({...f,[k]:v}));setDirty(true);};
 useEffect(()=>{const warn=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[dirty]);
 const close=()=>{if(!dirty||confirm('尚有未保存的修改，确定离开？'))onClose();};
 const save=async(e:React.FormEvent)=>{e.preventDefault();setSaving(true);setError('');try{const r=await post('records',{record:form,revision:initial.revision});setDirty(false);onSaved(r);}catch(e:any){setError(e.message);}finally{setSaving(false);}};
 return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)close();}}><section className="editor modal" role="dialog" aria-modal="true" aria-labelledby="editor-title"><header className="modal-head"><div><span className="eyebrow">MAKE IT YOURS</span><h2 id="editor-title">{initial.id?'编辑记录':'留下一点新的收获'}</h2></div><button className="icon-button" onClick={close} aria-label="关闭编辑器"><X/></button></header><form onSubmit={save}>
 <div className="form-row"><label>记录类型<select value={form.kind} onChange={e=>update('kind',e.target.value)}>{Object.entries(kinds).filter(([k])=>!['fortune','common'].includes(k)).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label>所属学科<select value={form.subject} onChange={e=>update('subject',e.target.value)}><option value="">综合</option>{Object.entries(subjects).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label>日期<input type="date" value={form.date} onChange={e=>update('date',e.target.value)}/></label></div>
 <label>标题<input autoFocus required maxLength={240} value={form.title} onChange={e=>update('title',e.target.value)} placeholder="一句话，记下最重要的内容"/></label>
 <div className="form-row"><label>主题 / 知识点<input value={form.topic} onChange={e=>update('topic',e.target.value)} placeholder="如：资料分析 · 增长率"/></label><label>标签（用逗号分隔）<input value={(form.tags||[]).join('，')} onChange={e=>update('tags',e.target.value.split(/[,，]/).map((s:string)=>s.trim()).filter(Boolean))}/></label></div>
 <label>正文 <span className="muted">支持 Markdown，原文与分析请分段填写</span><textarea rows={12} value={form.body} onChange={e=>update('body',e.target.value)} placeholder={form.kind==='review'?'## 实际表现\n\n## 原因\n\n## 纠正方法\n\n## 下一步行动':form.kind==='memory'?'问题写在标题，答案写在这里。':'记录理解、方法、易混点，或此刻的想法。'}/></label>
 <label>图片 / PDF 附件<input type="file" accept=".pdf,.png,.jpg,.jpeg,.webp" onChange={async e=>{const file=e.target.files?.[0];if(!file)return;setSaving(true);try{const buffer=new Uint8Array(await file.arrayBuffer());let binary='';for(let i=0;i<buffer.length;i+=32768)binary+=String.fromCharCode(...buffer.subarray(i,i+32768));const result=await post('upload',{filename:file.name,base64:btoa(binary),subject:form.subject});update('sourceRefs',[...form.sourceRefs,{sourceId:result.source.id,page:1,label:file.name,regions:[]}]);}catch(e:any){setError(e.message);}finally{setSaving(false);}}}/></label>
 <details className="editor-links" open={form.sourceRefs.length>0||form.links.length>0}><summary><Link2 size={15}/>关联来源与记录</summary>{form.sourceRefs.map((ref:SourceRef,i:number)=><div className="ref-edit" key={i}><span>{ref.label||catalog.sources.find(s=>s.id===ref.sourceId)?.title||ref.url||'附件'}{ref.page?` · 第 ${ref.page} 页`:''}{ref.regions?.length?` · ${ref.regions.length} 处标注`:''}</span><button type="button" className="text-button" onClick={()=>update('sourceRefs',form.sourceRefs.filter((_:any,n:number)=>n!==i))}>移除</button></div>)}<div className="form-row"><label>添加原资料<select value="" onChange={e=>{if(e.target.value)update('sourceRefs',[...form.sourceRefs,{sourceId:e.target.value,page:1,regions:[]}]);}}><option value="">选择资料…</option>{catalog.sources.map(s=><option key={s.id} value={s.id}>{s.title}</option>)}</select></label><label>添加原始网址<input type="url" placeholder="https://…" onBlur={e=>{if(/^https?:\/\//.test(e.target.value)){update('sourceRefs',[...form.sourceRefs,{url:e.target.value,label:'原始发布页'}]);e.target.value='';}}}/></label></div>
 <label>关联其他卡片 / 复盘<input value={relation} onChange={e=>setRelation(e.target.value)} placeholder="输入标题搜索"/></label>{relation&&<div className="relation-options">{catalog.records.filter(r=>r.id!==form.id&&r.title.includes(relation)&&!form.links.includes(r.id)).slice(0,8).map(r=><button type="button" key={r.id} onClick={()=>{update('links',[...form.links,r.id]);setRelation('');}}>{r.title}</button>)}</div>}{form.links.map((id:string)=><div className="ref-edit" key={id}><span>{catalog.records.find(r=>r.id===id)?.title||id}</span><button type="button" className="text-button" onClick={()=>update('links',form.links.filter((v:string)=>v!==id))}>移除</button></div>)}</details>
 {error&&<p className="error-message" role="alert">{error}</p>}<footer className="modal-footer"><span className="muted">保存到电脑后，可一键发布到阅读版。</span><button className="button primary" disabled={saving}>{saving?<LoaderCircle className="spin" size={16}/>:<Save size={16}/>} {saving?'正在处理…':'保存记录'}</button></footer></form></section></div>;
}
