import {useEffect,useRef,useState} from 'react';
import {ChevronLeft,ChevronRight,ZoomIn,ZoomOut,ExternalLink,Highlighter,Plus,RotateCw,Image as ImageIcon,LoaderCircle} from 'lucide-react';
import {sourcePages,isLocal}from'./api';
import type{Source,SourceRef,Region}from'./types';
export function Reader({source,reference,onRefChange,onCreate,onClose}:{source:Source;reference:SourceRef;onRefChange:(r:SourceRef)=>void;onCreate?:(r:SourceRef)=>void;onClose?:()=>void}){
 const page=reference.page||1;const [hd,setHd]=useState(false),[zoom,setZoom]=useState(1),[select,setSelect]=useState(false),[draft,setDraft]=useState<Region|null>(null),[error,setError]=useState(''),[metadata,setMetadata]=useState<any>(null),[pdfMode,setPdfMode]=useState(false),[rendering,setRendering]=useState(false),[rotation,setRotation]=useState(0);
 const frame=useRef<HTMLDivElement>(null),canvas=useRef<HTMLCanvasElement>(null),start=useRef<{x:number;y:number}|null>(null),pdfDocument=useRef<any>(null);
 useEffect(()=>{setError('');setRotation(0);setDraft(null);sourcePages(source.id).then(setMetadata).catch(()=>setMetadata(null));},[source.id]);
 useEffect(()=>{setDraft(null);setError('');setRotation(0);},[page]);
 useEffect(()=>{if(!pdfMode||source.kind!=='pdf')return;let stopped=false,task:any;setRendering(true);setError('');(async()=>{const pdf=await import('pdfjs-dist');pdf.GlobalWorkerOptions.workerSrc=new URL('pdfjs-dist/build/pdf.worker.min.mjs',import.meta.url).toString();if(!pdfDocument.current)pdfDocument.current=await pdf.getDocument({url:`/files/${source.id}`}).promise;const pg=await pdfDocument.current.getPage(page);if(stopped||!canvas.current)return;const viewport=pg.getViewport({scale:1.8});canvas.current.width=viewport.width;canvas.current.height=viewport.height;task=pg.render({canvas:canvas.current,viewport});await task.promise;if(!stopped)setRendering(false);})().catch(e=>{if(!stopped){setError('PDF 渲染失败：'+e.message);setRendering(false);}});return()=>{stopped=true;task?.cancel();};},[pdfMode,source.id,page]);
 useEffect(()=>()=>{pdfDocument.current?.destroy();pdfDocument.current=null;},[source.id]);
 const position=(e:React.PointerEvent)=>{const b=frame.current!.getBoundingClientRect();return{x:Math.max(0,Math.min(1,(e.clientX-b.left)/b.width)),y:Math.max(0,Math.min(1,(e.clientY-b.top)/b.height))};};
 const pageMeta=metadata?.pages?.find((p:any)=>p.pageNumber===page);const download=isLocal()?`/files/${source.id}`:source.downloadUrl;
 const regions=reference.regions||[];
 return <section className="reader" aria-label="原资料阅读器">
  <div className="reader-head"><div><span className="eyebrow">THE ORIGINAL · 原资料</span><h3>{source.title}</h3></div>{onClose&&<button className="icon-button" onClick={onClose} aria-label="关闭原资料">×</button>}</div>
  <div className="reader-toolbar"><button className="icon-button" disabled={page<=1} onClick={()=>onRefChange({...reference,page:page-1,regions:[]})} aria-label="上一页"><ChevronLeft size={18}/></button><label className="page-input"><input aria-label="页码" type="number" min="1" max={source.pageCount} value={page} onChange={e=>{const n=Number(e.target.value);if(n>=1&&n<=source.pageCount)onRefChange({...reference,page:n,regions:[]});}}/> / {source.pageCount}</label><button className="icon-button" disabled={page>=source.pageCount} onClick={()=>onRefChange({...reference,page:page+1,regions:[]})} aria-label="下一页"><ChevronRight size={18}/></button><span className="toolbar-gap"/><button className="icon-button" onClick={()=>setZoom(Math.max(.7,zoom-.2))} aria-label="缩小"><ZoomOut size={17}/></button><button className="icon-button" onClick={()=>setZoom(Math.min(2.4,zoom+.2))} aria-label="放大"><ZoomIn size={17}/></button><button className={hd?'chip active':'chip'} onClick={()=>setHd(!hd)}>高清</button><button className="icon-button" onClick={()=>{setRotation((rotation+90)%360);setSelect(false);}} aria-label="旋转页面"><RotateCw size={16}/></button></div>
  {isLocal()&&<div className="reader-actions"><button className={select?'chip active':'chip'} onClick={()=>{setRotation(0);setSelect(!select);}}><Highlighter size={14}/>{select?'正在框选':'框选原文'}</button>{source.kind==='pdf'&&<button className="chip" onClick={()=>setPdfMode(!pdfMode)}>{pdfMode?'轻量预览':'PDF 原页'}</button>}{regions.length>0&&<button className="chip" onClick={()=>onRefChange({...reference,regions:[]})}>清除选区</button>}{onCreate&&<button className="chip" onClick={()=>onCreate({...reference,sourceId:source.id,page,regions})}><Plus size={14}/>由此建卡</button>}</div>}
  <div className="reader-hint">{source.missing?'原文件缺失，请在电脑管理版重新关联。':regions.length?`已定位第 ${page} 页 · ${regions.length} 处原文标注`:select?'拖动框选原文，可连续添加多个区域。':'已定位原页 · 此页暂无区域标注'}</div>
  <div className="paper-scroll"><div className="paper" style={{width:`${zoom*100}%`,transform:`rotate(${rotation}deg)`,marginBlock:rotation%180?'22%':undefined}} ref={frame} onPointerDown={e=>{if(!select)return;e.preventDefault();frame.current?.setPointerCapture(e.pointerId);start.current=position(e);}} onPointerMove={e=>{if(!start.current)return;const end=position(e),s=start.current;setDraft({x:Math.min(s.x,end.x),y:Math.min(s.y,end.y),w:Math.abs(s.x-end.x),h:Math.abs(s.y-end.y)});}} onPointerUp={e=>{if(!start.current)return;const end=position(e),s=start.current;const r={x:Math.min(s.x,end.x),y:Math.min(s.y,end.y),w:Math.abs(s.x-end.x),h:Math.abs(s.y-end.y)};start.current=null;setDraft(null);if(r.w>.008&&r.h>.008)onRefChange({...reference,sourceId:source.id,page,regions:[...regions,r]});}} onPointerCancel={()=>{start.current=null;setDraft(null);}}>
   {pdfMode?<canvas ref={canvas}/>:<img key={`${source.id}-${page}-${hd}`} src={`./previews/${source.id}/${page}${hd?'-hd':''}.webp`} alt={`${source.title} 第 ${page} 页`} draggable="false" onError={()=>setError('此页预览尚未生成，可打开原文件查看。')} onLoad={()=>setError('')}/>}
   {[...regions,...draft?[draft]:[]].map((r,i)=><span key={i} className="highlight-region" style={{left:`${r.x*100}%`,top:`${r.y*100}%`,width:`${r.w*100}%`,height:`${r.h*100}%`}}/>)}
   {select&&<span className="selection-layer"/>}
  </div></div>
  {rendering&&<p className="inline-status"><LoaderCircle className="spin" size={16}/> 正在渲染原页…</p>}{error&&<p className="error-message">{error}</p>}
  {download&&<a className="text-link source-download" href={download} target="_blank" rel="noreferrer">下载完整原文件 <ExternalLink size={14}/></a>}
  {pageMeta&&<div className="page-metadata"><details><summary>原文与人工笔记</summary><p className="preserve">{pageMeta.rawText||pageMeta.sourceContent?.materialText||'本页没有可提取的文字层，请查看原页。'}</p>{pageMeta.sourceContent?.userHandwriting&&<p>手写记录：{pageMeta.sourceContent.userHandwriting}</p>}</details><details><summary>AI 整理 {pageMeta.manualReviewRequired?'· 待人工确认':''}</summary><p>{pageMeta.aiContent?.summary||'暂无整理'}</p><p>{(pageMeta.aiContent?.uncertainties||[]).join('；')}</p></details></div>}
 </section>;
}
